name: CI

on: [push, pull_request]

jobs:
    ci-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install ruff mypy pytest

            - name: Run Ruff Checks
              run: |
                  ruff check .
                  ruff format --check .

            - name: Run MyPy
              run: mypy .

            - name: Run Unit Tests
              run: pytest
